Minor fix to generator_pythia8_LF.C (#1731)
1. fixing : error: use of undeclared identifier 'nlohmann'
2. fixing : error: reference to 'Pythia' is ambiguous

(cherry picked from commit ab8d3edaabc6cb6c5a73656c0afb532ded1d7d26)